# Generated by Django 3.2.7 on 2021-09-11 10:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.FloatField()),
                ('time_to_cook', models.DurationField()),
                ('added_datetime', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('changed_datetime', models.DateTimeField(blank=True, default=None, null=True)),
                ('is_vegan', models.BooleanField(default=False)),
            ],
        ),
    ]
