# Generated by Django 3.2.7 on 2021-09-11 11:05

import api.models.custom_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='time_to_cook',
            field=api.models.custom_fields.ISODurationString(),
        ),
    ]
