# Generated by Django 3.2.7 on 2021-09-11 12:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_dish_time_to_cook'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('added_datetime', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('changed_datetime', models.DateTimeField(blank=True, null=True)),
                ('dishes', models.ManyToManyField(to='api.Dish')),
            ],
        ),
    ]
