# Generated by Django 3.2.7 on 2021-09-11 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='dishes',
            field=models.ManyToManyField(default=list, to='api.Dish'),
        ),
    ]
