# Generated by Django 3.2.7 on 2021-09-12 12:06

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_card_dishes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='changed_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='card',
            constraint=models.CheckConstraint(check=models.Q(('added_datetime__lte', django.db.models.expressions.F('changed_datetime'))), name='api_card_added_datetime_lte_changed_datetime'),
        ),
        migrations.AddConstraint(
            model_name='dish',
            constraint=models.CheckConstraint(check=models.Q(('added_datetime__lte', django.db.models.expressions.F('changed_datetime'))), name='api_dish_added_datetime_lte_changed_datetime'),
        ),
    ]
