# Generated by Django 3.2.7 on 2021-09-12 12:27

import api.models.custom_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210912_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='image',
            field=api.models.custom_fields.ImageStringField(blank=True, null=True),
        ),
    ]
